a = input()

print(a.find('a'),end=' ')
print(a.find('b'),end=' ')
print(a.find('c'),end=' ')
print(a.find('d'),end=' ')
print(a.find('e'),end=' ')
print(a.find('f'),end=' ')
print(a.find('g'),end=' ')
print(a.find('h'),end=' ')
print(a.find('i'),end=' ')
print(a.find('j'),end=' ')
print(a.find('k'),end=' ')
print(a.find('l'),end=' ')
print(a.find('m'),end=' ')
print(a.find('n'),end=' ')
print(a.find('o'),end=' ')
print(a.find('p'),end=' ')
print(a.find('q'),end=' ')
print(a.find('r'),end=' ')
print(a.find('s'),end=' ')
print(a.find('t'),end=' ')
print(a.find('u'),end=' ')
print(a.find('v'),end=' ')
print(a.find('w'),end=' ')
print(a.find('x'),end=' ')
print(a.find('y'),end=' ')
print(a.find('z'))
